   CREATE SEQUENCE SEQ_PRODUCTO;
   
   CREATE SEQUENCE SEQ_CLIENTE;
   
   CREATE SEQUENCE SEQ_DESEMBOLSO;
   
   CREATE SEQUENCE SEQ_DESEMBOLSO_DETALLE;

    CREATE SEQUENCE SEQ_USUARIO;

    CREATE SEQUENCE SEQ_AUTHORITY;

    CREATE SEQUENCE SEQ_USUARIO_AUTHORITY;